### ISSUE TITLE
Github Auth for k8s cluster

### ISSUE THREAD

**Issue by splattner** [acend/infrastructure#11]
Something similar to https://medium.com/preply-engineering/k8s-auth-a81f59d4dff6

but not sure if really needed or if simple SA is enought. Maybee with https://github.com/FairwindsOps/rbac-manager

**Comment by splattner** [comment]
For the moment, we decided to go with simple Service Account and tokens. See https://github.com/acend/infrastructure#cluster-access

Do you see a need for a external auth system?

**Comment by phil-pona** [comment]
SA is enough for now, we should think about a longterm solution, so that we can enforce 2FA and keep the identities synced over all our Services, to keep User and Permissionmanagement somehow central
