### ISSUE TITLE
Decision: Gitops Tool: FluxCD vs ArgoCD

### ISSUE THREAD

**Issue by splattner** [acend/infrastructure#27]
As of now, we chose to use [FluxCD](https://fluxcd.io/) as the GitOps tool to deploy our Kubernetes infrastructure related tools in this IaC repository. For full team alignment, I wan't to open the discussion if this is the right choice or if [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) as the alternate shall be chosen.

**History:**
For other projects at Puzzle and also for our training cluster (see https://github.com/acend/training-setup) we have (often) chosen ArgoCD as the GitOps tool. Therefore FluxCD is a new tool. But operational experience with FluxCD is also existing (in customer projects and private projcts)

A good comparison of both tools can be found [here](https://earthly.dev/blog/flux-vs-argo-cd/)

**Why we want to use FluxCD for this project:**
- Extend our knowhow/portfolio and experience
- Operational complexity, FluxCD feels more slim (no WebUI, no RBAC on top of K8s, full configuration as CRD), although I guess this is my personal opinion.
- Already mentioned above, relies on RBAC of Kubernetes and does not have its own RBAC System (which is a bit strange to configure) on top (as ArgoCD). ArgoCD also includes a User Authentication on top (local argocd user or Oauth), which is not required in our setup as we have a small user group and no multi-tenant requirement.
- We have a simple isolated setup used for only this cluster. Not much code-reuse possible from the cluster-training setup possible

**Reasons for not choosing FluxCD:**
- A new tool, with (slightly) less experience than ArgoCD

**So, open points for discussion:**
- Is everybody ok with this decision?
- If not, why? Is it a No GO or can you live with it?
- Do you see (huge) other problems/pro & cons with one of the tools?

**Comment by phil-pona** [comment]
To get it straight, I'm **not** ok with this solution, I might need a bit more time to get my full aspects to this on paper. Here are a couple of my thoughts:

- We teach Argo CD at customers
- ArgoCD it's production proven at many of our customers including the puzzle env
- we have a lot more knowledge with ArgoCD than we have with Flux
- It's the interface for other acendees to help with the cluster, many of us know ArgoCD
- it's quite risky to test a new technology on a production env, do you plan on having test clusters as well? How will update be tested?
- We should not extend our knowhow/portfolio in production, our services are very critical for the acend business
- It's the same tooling as we're going to use for the lab infra, it will mean a lot of synergies. This will lead to a lot more Operational complexity, if we use two toolset for the same purpose

So for me, it's a clear NO-GO, and it pretty much feels for me like a déjà vu.

And honestly I would rather go with terraform applying the helm charts and resources than adding another toolset only to test it out on a production and essential Setup

**Comment by splattner** [comment]
I'll already reply to some of your input (just so It's already written and other might see more points to discuss). But we can discuss it in personal later in the next S1 Meeting:
 
>     * ArgoCD it's production proven at many of our customers including the puzzle env

In general, FluxCD is equally production proven with a lot of other customer (maybee just not with our peers). Both projects are graduated CNCF Projects.

>     * It's the interface for other acendees to help with the cluster, many of us know ArgoCD

Only by knowing ArgoCD, you cannot operate a Kubernetes Cluster. I think there is much more to know in order to help with the cluster than knowing how the delivery mechanism works. When you know how to configure components for a k8s cluster with ArgoCD, then you also know how to configure it with FluxCD (its just plain Kubernetes Resources, Helm Charts, Kustomize)

>     we have a lot more knowledge with ArgoCD than we have with Flux
>     * it's quite risky to test a new technology on a production env, do you plan on having test clusters as well? How will update be tested?

Yes, there is a task in the Todo List on the project page (currently as Draft) for the Staging Cluster. And as it is a graduated project, this is not a big risk (for me its the same as with ArgoCD), the technology itself is not new (v1 of Flux is even older than ArgoCD) Only to some of us, but yes, we have less operational Know How with FluxCD. I agree

>     * It's the same tooling as we're going to use for the lab infra, it will mean a lot of synergies. This will lead to a lot more Operational complexity, if we use two toolset for the same purpose

I don't agree here. I currently don't see that many synergies, its just the delivery mechanism. The complexity is withing the installed component and the cluster setup it self.

**Comment by splattner** [comment]
After a night of sleep ;) I think we don't need to spend more time on this. If it's a NO-GO for you, that's legit, no need to convince you. I'm also fine with ArgoCD.

I'll leave the issue open a couple more days. But if no other votes are coming in the decision is ArgoCD.

**Comment by bliemli** [comment]
I don't even know why we're talking about this...
